name: Main App Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.1
          bundler-cache: true
      - name: Install dependent libraries
        run: sudo apt-get install libpq-dev
      - name: Ruby gem cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install gems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Setup Database
        run: |
          cp config/database.yml.github-actions config/database.yml
          bin/rails db:prepare
        env:
          RAILS_ENV: test
          PG_USER: postgres
          PG_PASSWORD: postgres
          PG_HOST: localhost
          PG_PORT: 5432
      - name: Run tests
        run: |
          bin/rails zeitwerk:check
          bin/rails test
        env:
          RAILS_ENV: test
          PG_USER: postgres
          PG_PASSWORD: postgres
          PG_HOST: localhost
          PG_PORT: 5432
